import type { Metadata } from 'next'

export const defaultMetadata: Metadata = {
	title: {
		default: 'Neue Website',
		template: '%s | Neue Website',
	},
	description: 'Generated by create next app',
}

